CREATE TABLE RELATIONSHIP (
    ID NUMBER,
    CONSTRAINT RELATIONSHIP_ID PRIMARY KEY (id),
    USER_ID_FROM NUMBER,
    STATUS NVARCHAR2 (20) CHECK(STATUS = 'WAS_FRIEND' OR STATUS = 'REQEST_SENT' OR STATUS = 'REQEST_DENIED' OR STATUS = 'FRIEND'),
    CONSTRAINT USER_ID_FROM_FK FOREIGN KEY (USER_ID_FROM) REFERENCES USERS (ID),
    USER_ID_TO NUMBER,
    CONSTRAINT USER_ID_TO_FK FOREIGN KEY (USER_ID_TO) REFERENCES USERS (ID)
);