CREATE TABLE MESSAGE (
    ID NUMBER,
    CONSTRAINT MESSAGE_ID PRIMARY KEY (id),
    TEXT NVARCHAR2 (300),
    DATE_SENT DATE,
    DATE_READ DATE,
    USER_FROM NUMBER,
    CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM) REFERENCES USERS (ID),
    USER_TO NUMBER,
    CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO) REFERENCES USERS (ID)
);